// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DebugDataViewCore
{
    internal sealed partial class Vsix
    {
        public const string Id = "DebugDataViewCore.5d8e80e3-2bda-4370-851c-7f51286f5ddd";
        public const string Name = "DebugDataViewCore";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "贝贝 关";
        public const string Tags = "";
    }
}
