// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DebugDataViewCore
{
    internal sealed partial class Vsix
    {
        public const string Id = "DebugDataViewCore.5d8e80e3-2bda-4370-851c-7f51286f5ddd";
        public const string Name = "DebugDataViewCore";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "beibei guan";
        public const string Tags = "";
        public const bool IsPreview = false;
    }
}
